### ISSUE TITLE
Out of memory...

### ISSUE THREAD

**Issue by GGRIZLI** [SpoturDeal/MMM-Fibaro#1]
When i use Fibaro module in MagicMirror (MMM-Fibaro) I get after 7-8 hours Out Of Memory error and screen become black. When i press CTRL + R to reload or restart MagicMirror then is OK again with 7-8 hours, then again black screen... If I delete Fibaro module from MagicMirror then is all OK... I was testing fibaro module like it is... How to solve this problem?

**Comment by SpoturDeal** [comment]
Hello @GGRIZLI ,

Sorry to hear the module is giving you problems. I am not able to reproduce your error
can you install MMM-SystemStats
and check if the memory  is filling up. This apps shows stats of memory use if it fills up slowly you would see Free RAM getting smaller over days.

**Comment by GGRIZLI** [comment]
Hi.

 

Yes, in log I see that FIBARO_READ shows up constantly and then after 7-8 hours shows up OUT OF MEMORY ERROR (in log) and screen become black. After Restart MM (CTRL+R) then is all ok with another 7-8 hours.... If I disable FIBARO module, then all is OK...

 

Yes, I can install MMM-SystemStats and we will see whats happend. Tnx for now...

 

BR,

GRIZLI

**Comment by GGRIZLI** [comment]
Hi... 

 

I've installed MMM-SystemStats module on MM and here is some pictures...

 

When monitor is OFF then CPU temp is about 55-60˙C, when is ON then CPU temp is about 80-82˙C. Monitor is connected via HDMI cable.

 

And here is some pictures of MM Log file. When I start MM, between 4-5 hours and what's hapends on about 7-8 hours....

When Fatal error – out of memory shows up, screen of MM goes black, only mouse cursor is visible. When I press CTRL+R to restart MM, then is all OK about 7-8 hours and then again...

 

 

Is there any solution?

 

BR,

 

GRIZLI

**Comment by SpoturDeal** [comment]
Hi,

I have just uploaded a new version.
the thing is that I gave up on Fibaro and switch to Domoticz and am not using the module anymore, however i made a small change in the script.

The only parts that consume memory are some variables

therefor i try to delete them line 66 tot 68

```
delete text;
delete power;
delete data; 

```

It is possible that this will give an error as well because data is an object that is not defined by var.
If this error appears just remark the line out with double /

Let me know if it works.

**Comment by GGRIZLI** [comment]
Hi. 

 

TNX. I will try today and let you know.

 

Tnx again.

**Comment by GGRIZLI** [comment]
Hi.

 

Just wondering.

 

I use Fibaro Home Center now about 4 years and I have all Fibaro modules except some Multisensor 6 from AEOTEC... I looking to other alternatives now, because Fibaro seems to sleep. But yesterday, someone from Fibaro get some info about something new, something that Fibaro push back to No. 1... But we must waiting...a little....

 

So, how domoticz work and what i need to start up???

**Comment by SpoturDeal** [comment]
Hello 

My fibaro froze, did a few fully restarts but always after 3 or 4 months it gave me problems.

I build my domoticz on a Raspberry Pi 3
with an AEON LABS USB Z-WAVE PLUS CONTROLLER  around 45€   (https://www.robbshop.nl/aeon-labs-usb-adapter-op-batterijen-en-zwave-plus)

The Fibaro used 45 to 60 Watt in normal operation my Raspberry less then 10 Watt. it runs on a 12Volt 1A power supply.

Just download the software from domoticz.com  (https://www.domoticz.com/downloads/)

I have implemented a MQTT server and Node-red (All free) (https://www.domoticz.com/wiki/MQTT)

Am able to connect all kind of devices I have Z-Wave and WIFI devices even use some pins from the Raspberry to detect my mailbox opening and some-one ringing my front door.

It works with all Fibaro devices.

Good luck

**Comment by GGRIZLI** [comment]
Hi.

 

I have both home – The RPI and USB z-wave stick. Well, when i have more free time, then i will try...

 

Now, I testing changed MMM-Fibaro module, but i must wait about 7 hours L

 

Tnx,

 

BR,

GRIZLI

**Comment by GGRIZLI** [comment]
Hi.

 

I just want to inform you, that OUT OF MEMORY error still exists, and blank screen appears on MM L

 

BR,

GRIZLI
